### ISSUE TITLE
Не работает свежесобранное приложение lib\iracli\src\Модули\ПараметрыПриложения.os / Ошибка в строке: 16,0 / Библиотека не найдена: '../../config'}

### ISSUE THREAD

**Issue by Ndochp** [arkuznetsov/iracli#1]
Версия (коммит) 3ce6ed70e9268e92e99a815bf6842c7ee2487e67
При сборке (opm build) и установке (opm i iracli-0.6.0.ospx ) в библиотеки не попадает папка iracli\config
После чего запуск падает с 
```
C:\GIT_REPO\iracli>iracli.bat /?
{Модуль C:\soft\OneScript\lib\iracli\src\Модули\ПараметрыПриложения.os / Ошибка в строке: 16,0 / Библиотека не найдена: '../../config'}
```
Что тут ошибка - сборка забыла папку или приложение должно работать без папки - не знаю.

**Comment by arkuznetsov** [comment]
Опубликовал релиз, добавил каталог в сборку.

**Comment by Ndochp** [comment]
Все работает, спасибо.
